POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsZXgiLCJpZCI6IjY1NjBiNTIwNTU1NmFjZjdlZmY2NDk0ZCIsImlhdCI6MTcwMDgzNzE2Mn0.iXxcsxotYpKS2MOW2vwGC5zvq7M3KldfdywbLYsUCF4

{
  "title": "33333",
  "author": "logggggg",
  "url": "logggggg",
  "likes": 5
}